# Etude d'un système planétaire
 
**Lehanneur Iona - Blasco Anaïs - Daumont Jean-Baptiste**
*ARE DYNAMIC - 2021*

## Préambule

Un système planétaire tout comme celui dans lequel nous évoluons, se compose de corps célestes (astéroïdes, comètes…). Tous gravitent autour d’une étoile centrale.
Ce projet de recherche documentaire a pour objectif de déterminer de quelle manière des facteurs tels que la taille d’un système complet, la masse et le diamètre de l’étoile centrale et le nombre de planètes influent sur les différentes trajectoires des corps célestes.
Pour ce faire, nous utiliserons différentes métriques via le langage de programmation Python dans le but de comparer différents systèmes modélisés par nos soins. Nous en déduirons à partir de quelle masse, l’astre central est trop « léger » pour attirer les corps et inversement, à partir de quelle masse et taille se trouve-t-il trop « gros » pour que les planètes n’entrent pas en collision avec ce dernier.

La taille et le nombre de planètes ont aussi un rôle essentiel à jouer, nos hypothèses soutiennent qu’un système trop grand comparé à la taille de l’étoile, empêchera les planètes lointaines d’engendrer une orbite stable, ainsi, les plus éloignées ne feront plus partie du système étudié.
En somme, nous conclurons avec des courbes significatives, montrant le comportement des astres quant à la modification des paramètres cités précédemment, ce qui constituera la réponse à notre problématique.


## Objectifs

Dans ce notebook nous allons essayer de modéliser les trajectoires des planètes avec l'aide de formules mathématiques concrètes, afin que notre modèle mette en lumière les différences d'un système à l'autre. Nous allons essayer de comprendre les différentes façons d'implémenter un modèle significatif, et d'obtenir des résultats commentés qui permettront de comprendre dans quelles mesures un système va-t-il émerger, et sous quelle(s) condition(s) va-t-il pouvoir accueillir un nombre de planètes plus élevé que le notre.



#  Etude du modèle en deux dimensions

**Objectifs : implémenter le modèle planétaire en python, le tester sur un exemple simple puis étudier l'impact que peuvent avoir les paramètres du modèle sur le système.**

Nous allons étudier l’impact des paramètres du modèle : 
- la taille du système,
- le nombre de planètes,
- le diamètre de l'étoile,
- la masse de l'étoile,

**Pour quantifier l'impact de ces paramètres, en plus de l'observation visuelle de l'évolution de notre système, nous utiliserons les métriques suivantes :**


In [1]:
import numpy as np

from math import sqrt

import random

from matplotlib import pyplot as plt

import turtle

In [2]:
# Paramètres du modèle Planétaire
sysize = 11    # Taille du système
plannum= 3    # Nombre de planètes (pour planet number à l'anglaise évidemment)
diameter=2    # Diamètre de l'étoile centrale en kms
mass=10^30 # Masse de l'étoile centrale

**Notre système est composé d'une matrice carrée de taille sysize.**

In [3]:
system=np.zeros((sysize,sysize),dtype=int)
print (system)

[[0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]]


**la fonction ```print_system``` permet d'afficher le système.**


In [4]:
def print_system(system):
    result = ""
    for i in system:
        for j in i:
            result += " "+str(j)
        result += " "+'\n'
    print(result)
    return
print_system(system)

 0 0 0 0 0 0 0 0 0 0 0 
 0 0 0 0 0 0 0 0 0 0 0 
 0 0 0 0 0 0 0 0 0 0 0 
 0 0 0 0 0 0 0 0 0 0 0 
 0 0 0 0 0 0 0 0 0 0 0 
 0 0 0 0 0 0 0 0 0 0 0 
 0 0 0 0 0 0 0 0 0 0 0 
 0 0 0 0 0 0 0 0 0 0 0 
 0 0 0 0 0 0 0 0 0 0 0 
 0 0 0 0 0 0 0 0 0 0 0 
 0 0 0 0 0 0 0 0 0 0 0 



**Notre étoile centrale est donc située au entre du système (ici matrice), elle est représentée grâce à ses coordonnées.**

In [5]:
coord_star = sysize//2

**La fonction ```create_etoile```place l'étoile au centre du système selon ses coordonnées. Le coté du carré sensé représenter l'étoile fera le diamètre de l'étoile (exemple diamètre=3: carré=3x3 dans le système).**

In [6]:
def create_etoile(system):
    
    system[coord_star-diameter//2:coord_star+diameter//2+1, coord_star-diameter//2:coord_star+diameter//2+1] = 1

In [7]:
create_etoile(system)

In [8]:
print_system(system)

 0 0 0 0 0 0 0 0 0 0 0 
 0 0 0 0 0 0 0 0 0 0 0 
 0 0 0 0 0 0 0 0 0 0 0 
 0 0 0 0 0 0 0 0 0 0 0 
 0 0 0 0 1 1 1 0 0 0 0 
 0 0 0 0 1 1 1 0 0 0 0 
 0 0 0 0 1 1 1 0 0 0 0 
 0 0 0 0 0 0 0 0 0 0 0 
 0 0 0 0 0 0 0 0 0 0 0 
 0 0 0 0 0 0 0 0 0 0 0 
 0 0 0 0 0 0 0 0 0 0 0 



**Pour créer une planète, nous nous servons d'une classe planète.**

**On obtient ici la vitesse à l'aide de la formule pour les vitesses orbitales où G est la constante de gravitation universelle , et d la distance entre les noyaux de la planète et l'étoile**

In [9]:
G = 6.6742*10**-11

In [10]:
class planetetype():

    def __init__(self):
        # self fait référence à l'objet lui-même
        self.sizeplan = random.randint(1,7)*0.01
        self.coordonnees = [random.randint(0,sysize-1),random.randint(0,sysize-1)]
        self.massplan = random.randint(10**20,10**28)
        self.d = sqrt((self.coordonnees[0]-coord_star)**2+(self.coordonnees[1]-coord_star)**2)
        self.vitesse = sqrt(G*self.massplan)/self.d

**La fonction ``rand_plan`` permet de créer les planètes de notre système en fonction de *plannum*, et de lui prodiguer une masse random dans un intervalle réaliste (la planète ne peut être plus lourde que l'étoile centrale), ainsi qu'un diamètre plausible (même raisonnement).**

In [11]:
def randplan(plannum):
    L=[]
    while (plannum!=0):
        planete=planetetype()
        if system[planete.coordonnees[0],planete.coordonnees[1]]==0:
            plannum-=1
            L.append(planete)
    return (L)

In [12]:
L=randplan(plannum)

In [13]:
def create_p(plannum):
    for i in range (plannum):
        p=L[i].coordonnees
        system[p[0],p[1]]=2
    return system

In [14]:
create_p(plannum)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0],
       [0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [15]:
print_system(system)

 0 0 0 0 0 0 0 0 0 0 0 
 0 0 0 0 0 0 0 0 0 2 0 
 0 0 0 0 0 0 0 0 0 0 0 
 0 0 0 0 0 0 0 0 0 2 0 
 0 0 0 0 1 1 1 0 0 0 0 
 0 0 0 0 1 1 1 0 0 0 0 
 0 0 0 0 1 1 1 0 0 0 0 
 0 0 0 0 0 0 0 0 0 2 0 
 0 0 0 0 0 0 0 0 0 0 0 
 0 0 0 0 0 0 0 0 0 0 0 
 0 0 0 0 0 0 0 0 0 0 0 



**Les trajectoires circulaires des planètes sont représentées ici**

In [16]:
tur = turtle.Turtle()
   
        
import turtle
tur = turtle.Turtle()
couleurs=["blue","cyan","red","pink","orange"]
rayon = 1

for i in range (10):
    tur.color("yellow")
    tur.circle(rayon)
    tur.up ()
    tur.right(90)
    tur.forward(1)
    tur.left(90)
    tur.down ()
    rayon+=1


tur.up ()
tur.right(90)
tur.forward(50)
tur.left(90)
tur.down ()
rayon+=50
for i in range(plannum):
    tur.color(random.choice(couleurs))
    tur.circle(rayon)
    tur.up ()
    tur.right(90)
    tur.forward((L[i+1].d-L[i].d))
    tur.left(90)
    tur.down ()
    rayon+=(L[i+1].d-L[i].d)

IndexError: list index out of range

**Maintenant que nous avons un système et les trajectoires de nos planètes, il est temps de se demander: "comment nos facteurs influent-ils sur les trajectoires orbitales de nos planètes ?".**

**La fonction ``is_orbite`` sert à determiner si une planète est en orbite où non**

In [ ]:
def is_orbite(p):
    print((G*mass*p.massplan)/p.d**2,(p.massplan*p.vitesse**2)/p.d)
    if ((G*mass*p.massplan)/p.d**2==(p.massplan*p.vitesse**2)/p.d):
        return True
    else:
        return False

In [ ]:
is_orbite(L[2])

**La fonction ``compteur`` compte le nombre de planètes en orbite**

In [ ]:
def compteur(plannum):
    c=0
    for i in L:
        if is_orbite(i) == True:
            c+=1
    return c

In [ ]:
c=compteur(plannum)

**Pour cela, nous proposons une série de tests et les graphiques suivants:**

**TEST 1: La masse minimale de l'étoile**

In [ ]:
%matplotlib inline
Y=[]
X=[]
for i in range(plannum):
    X.append(i)

for i in range (c):
    Y.append(i)
    
plt.plot(X,Y)
plt.xlabel("Masse Etoile")
plt.ylabel("Nombre de planètes en orbite")
plt.show()

**TEST 2 : Le diamètre minimal de l'étoile**

In [ ]:
%matplotlib inline
Y=[]
X=[]
for i in range(diameter):
    X.append(i)

for i in range(c):
    Y.append(i)
    
plt.plot(X,Y)
plt.xlabel("diamètre Etoile")
plt.ylabel("Nombre de planètes en orbite")
plt.show()

**TEST 3: La taille du système**

In [ ]:
%matplotlib inline
Y=[]
X=[]
if sysize>diameter+diameter*4:
    for i in range(sysize):
        X.append(i)

for i in range(c):
    Y.append(i)
    
plt.plot(X,Y)
plt.xlabel("taille du monde")
plt.ylabel("Nombre de planètes en orbite")
plt.show()